image: python:3.8

before_script:
  - pip3 install .
  - pip3 install pytest

test:
    script: 
        - pytest

deploy:
    only:
    - main
    script: 
    - echo $PYPIRC > /tmp/.pypirc
    - cat /tmp/.pypirc
    - pip3 install twine
    - python3 setup.py  bdist_wheel
    - TWINE_USERNAME=$TWINE_USERNAME TWINE_PASSWORD=$TWINE_PASSWORD python3 -m twine upload dist/* --repository pypi --config-file /tmp/.pypirc
